module.exports = {
  user: {
    name: 'duncantest10',
    review_count: 33,
    api_key: '5fa2d9c257dda131a54018f5c3f5ff90',
    api_valid: true,
    join_date: '2012-07-04',
    last_wanikani_sync_date: '2016-06-08T04:32:37.856081Z',
    level: 33,
    unlocked_levels: ['33'],
    follow_me: true,
    auto_advance_on_success: true,
    auto_expand_answer_on_success: true,
    auto_expand_answer_on_failure: true,
    only_review_burned: false,
    on_vacation: false,
    vacation_date: null,
  },
  messages: [],
  reviews: {
    count: 33,
    results: [
      {
        id: 1,
        vocabulary: {
          meaning: 'stickiness',
          readings: [
            {
              character: '粘り',
              kana: 'ねばり',
              level: 49,
              tags: [
                'Noun',
              ],
              sentence_en: 'Will everyone please stick with it to the last moment.',
              sentence_ja: 'どうぞ皆様も最後の一瞬まで粘り抜いてください',
              jlpt: 'JLPT N1',
              common: true,
            },
          ],
        },
        answer_synonyms: [
          {
            id: 3,
            character: '弾丸',
            kana: 'だんがん',
            review: 8657,
          },
        ],
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-12-22T04:23:28.211404Z',
        needs_review: true,
        unlock_date: '2016-12-22T04:23:28.210789Z',
        next_review_date: '2016-12-22T04:23:28.229761Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'apprentice',
        wanikani_srs_numeric: 3,
        wanikani_burned: false,
        notes: null,
        user: 1,
      },
      {
        id: 2,
        vocabulary: {
          meaning: 'granny, grandma, old lady, old woman',
          readings: [
            {
              character: 'お婆ちゃん',
              kana: 'おばあちゃん',
              level: 49,
              tags: [
                'Noun',
              ],
              sentence_en: "They say that I'm an old woman.",
              sentence_ja: 'あの人たちは私のことをおばあちゃんだと言う',
              jlpt: null,
              common: true,
            },
          ],
        },
        answer_synonyms: [
          {
            id: 3,
            character: '弾丸',
            kana: 'だんがん',
            review: 8657,
          },
        ],
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-12-22T04:23:28.380790Z',
        needs_review: true,
        unlock_date: '2016-12-22T04:23:28.380457Z',
        next_review_date: '2016-12-22T04:23:28.395121Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'guru',
        wanikani_srs_numeric: 5,
        wanikani_burned: false,
        notes: null,
        user: 1,
      },
      {
        id: 3,
        vocabulary: {
          meaning: 'hatred',
          readings: [
            {
              character: '憎しみ',
              kana: 'にくしみ',
              level: 49,
              tags: [
                'Noun',
              ],
              sentence_en: 'Love is blind. Hatred is also blind.',
              sentence_ja: '恋は盲目憎しみもまたしかり',
              jlpt: 'JLPT N1',
              common: true,
            },
          ],
        },
        answer_synonyms: [
          {
            id: 3,
            character: '弾丸',
            kana: 'だんがん',
            review: 8657,
          },
        ],
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-12-22T04:23:28.481247Z',
        needs_review: true,
        unlock_date: '2016-12-22T04:23:28.480750Z',
        next_review_date: '2016-12-22T04:23:28.496418Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'apprentice',
        wanikani_srs_numeric: 2,
        wanikani_burned: false,
        notes: null,
        user: 1,
      },
      {
        id: 4,
        vocabulary: {
          meaning: 'red light district, pleasure quarters, world of the geisha',
          readings: [
            {
              character: '花柳界',
              kana: 'かりゅうかい',
              level: 49,
              tags: [
                'Noun',
              ],
              sentence_en: 'I’ve always dreamed of experiencing the red-light district.',
              sentence_ja: '花柳界を経験してみるのが夢だったんだ。',
              jlpt: null,
              common: false,
            },
          ],
        },
        answer_synonyms: [
          {
            id: 3,
            character: '弾丸',
            kana: 'だんがん',
            review: 8657,
          },
        ],
        correct: 1,
        incorrect: 0,
        streak: 1,
        last_studied: '2016-12-31T02:32:48.631861Z',
        needs_review: false,
        unlock_date: '2016-12-22T04:23:28.582129Z',
        next_review_date: '2016-12-31T06:45:00.647746Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'guru',
        wanikani_srs_numeric: 5,
        wanikani_burned: false,
        notes: null,
        user: 1,
      },
      {
        id: 5,
        vocabulary: {
          meaning: 'to pity, to have mercy on',
          readings: [
            {
              character: '哀れむ',
              kana: 'あわれむ',
              level: 49,
              tags: [
                'Godan verb',
                'Transitive verb',
              ],
              sentence_en: 'Some pitied them.',
              sentence_ja: '彼らあわれむ者もいた',
              jlpt: null,
              common: true,
            },
          ],
        },
        answer_synonyms: [
          {
            id: 3,
            character: '弾丸',
            kana: 'だんがん',
            review: 8657,
          },
        ],
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-12-22T04:23:28.687532Z',
        needs_review: true,
        unlock_date: '2016-12-22T04:23:28.687183Z',
        next_review_date: '2016-12-22T04:23:28.702754Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'guru',
        wanikani_srs_numeric: 5,
        wanikani_burned: false,
        notes: null,
        user: 1,
      },
      {
        id: 6,
        vocabulary: {
          meaning: 'grudge, resentment, malice',
          readings: [
            {
              character: '恨み',
              kana: 'うらみ',
              level: 49,
              tags: [
                'Noun',
              ],
              sentence_en: 'The resentment runs deep.',
              sentence_ja: '恨みは深いですよ',
              jlpt: 'JLPT N2',
              common: true,
            },
          ],
        },
        answer_synonyms: [
          {
            id: 3,
            character: '弾丸',
            kana: 'だんがん',
            review: 8657,
          },
        ],
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-12-22T04:23:28.789825Z',
        needs_review: true,
        unlock_date: '2016-12-22T04:23:28.789422Z',
        next_review_date: '2016-12-22T04:23:28.804792Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'guru',
        wanikani_srs_numeric: 5,
        wanikani_burned: false,
        notes: null,
        user: 1,
      },
      {
        id: 7,
        vocabulary: {
          meaning: 'ceramic art, ceramics',
          readings: [
            {
              character: '陶芸',
              kana: 'とうげい',
              level: 49,
              tags: [
                'Noun',
              ],
              sentence_en: "Saturday is the pottery class I've been attending since last year.",
              sentence_ja: '土曜日去年から通い始めた陶芸教室',
              jlpt: null,
              common: true,
            },
          ],
        },
        answer_synonyms: [
          {
            id: 3,
            character: '弾丸',
            kana: 'だんがん',
            review: 8657,
          },
        ],
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-12-22T04:23:28.937608Z',
        needs_review: true,
        unlock_date: '2016-12-22T04:23:28.937272Z',
        next_review_date: '2016-12-22T04:23:28.965845Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'apprentice',
        wanikani_srs_numeric: 3,
        wanikani_burned: false,
        notes: null,
        user: 1,
      },
      {
        id: 8,
        vocabulary: {
          meaning: 'rest',
          readings: [
            {
              character: '憩い',
              kana: 'いこい',
              level: 49,
              tags: [
                'Noun',
              ],
              sentence_en: 'I want to make my restaurant a place of rest and relaxation for busy salarymen.',
              sentence_ja: '私はうちの食堂を忙しいサラリーマンの憩いの場にしたいんです。',
              jlpt: null,
              common: true,
            },
          ],
        },
        answer_synonyms: [
          {
            id: 3,
            character: '弾丸',
            kana: 'だんがん',
            review: 8657,
          },
        ],
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-12-22T04:23:29.106703Z',
        needs_review: true,
        unlock_date: '2016-12-22T04:23:29.106292Z',
        next_review_date: '2016-12-22T04:23:29.132362Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'guru',
        wanikani_srs_numeric: 5,
        wanikani_burned: false,
        notes: null,
        user: 1,
      },
      {
        id: 9,
        vocabulary: {
          meaning: 'dimness, obscurity, unclear, unintelligible',
          readings: [
            {
              character: '不明瞭',
              kana: 'ふめいりょう',
              level: 49,
              tags: [
                'Noun',
                'Na adjective',
              ],
              sentence_en: 'The result of this experiment is obscured by the extra variables added in the formula.',
              sentence_ja: '式に余分の変数を加えたことによってこの実験結果は不明瞭なものになっている',
              jlpt: null,
              common: false,
            },
          ],
        },
        answer_synonyms: [
          {
            id: 3,
            character: '弾丸',
            kana: 'だんがん',
            review: 8657,
          },
        ],
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-12-22T04:23:29.264851Z',
        needs_review: true,
        unlock_date: '2016-12-22T04:23:29.264489Z',
        next_review_date: '2016-12-22T04:23:29.292087Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'apprentice',
        wanikani_srs_numeric: 3,
        wanikani_burned: false,
        notes: null,
        user: 1,
      },
      {
        id: 10,
        vocabulary: {
          meaning: 'old age',
          readings: [
            {
              character: '老齢',
              kana: 'ろうれい',
              level: 38,
              tags: [
                'Noun',
                'No adjective',
              ],
              sentence_en: 'He is worn with age.',
              sentence_ja: '老齢で弱っている',
              jlpt: null,
              common: true,
            },
          ],
        },
        answer_synonyms: [
          {
            id: 3,
            character: '弾丸',
            kana: 'だんがん',
            review: 8657,
          },
        ],
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-12-22T04:24:15.127091Z',
        needs_review: true,
        unlock_date: '2016-12-22T04:24:15.126519Z',
        next_review_date: '2016-12-22T04:24:15.138863Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'enlighten',
        wanikani_srs_numeric: 8,
        wanikani_burned: false,
        notes: null,
        user: 1,
      },
      {
        id: 11,
        vocabulary: {
          meaning: 'evening edition',
          readings: [
            {
              character: '夕刊',
              kana: 'ゆうかん',
              level: 38,
              tags: [
                'Noun',
              ],
              sentence_en: 'My father sat reading the evening paper.',
              sentence_ja: '父は夕刊を読んで座っていた',
              jlpt: 'JLPT N2',
              common: true,
            },
          ],
        },
        answer_synonyms: [
          {
            id: 3,
            character: '弾丸',
            kana: 'だんがん',
            review: 8657,
          },
        ],
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-12-22T04:24:15.208012Z',
        needs_review: true,
        unlock_date: '2016-12-22T04:24:15.207493Z',
        next_review_date: '2016-12-22T04:24:15.227505Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'enlighten',
        wanikani_srs_numeric: 8,
        wanikani_burned: false,
        notes: null,
        user: 1,
      },
      {
        id: 12,
        vocabulary: {
          meaning: 'nara prefecture',
          readings: [
            {
              character: '奈良県',
              kana: 'ならけん',
              level: 38,
              tags: [
                'Proper noun',
              ],
              sentence_en: 'The Takamatuzuka burial mound is located in Nara prefecture, Asukamura.',
              sentence_ja: '古墳は県に存在する古墳',
              jlpt: null,
              common: false,
            },
          ],
        },
        answer_synonyms: [
          {
            id: 3,
            character: '弾丸',
            kana: 'だんがん',
            review: 8657,
          },
        ],
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-12-22T04:24:15.285349Z',
        needs_review: true,
        unlock_date: '2016-12-22T04:24:15.285013Z',
        next_review_date: '2016-12-22T04:24:15.341436Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'enlighten',
        wanikani_srs_numeric: 8,
        wanikani_burned: false,
        notes: null,
        user: 1,
      },
      {
        id: 13,
        vocabulary: {
          meaning: 'evacuation',
          readings: [
            {
              character: '避難',
              kana: 'ひなん',
              level: 38,
              tags: [
                'Noun',
                'Suru verb',
              ],
              sentence_en: 'The flow of evacuation events from occurrence of a large earthquake to the conclusion of emergency counter measures.',
              sentence_ja: '大地震の発生から応急対策の収束までの避難の流れです',
              jlpt: 'JLPT N1',
              common: true,
            },
            {
              character: '疎開',
              kana: 'そかい',
              level: 54,
              tags: [
                'Noun',
                'Suru verb',
              ],
              sentence_en: 'They were evacuated to the countryside to avoid the air raids.',
              sentence_ja: '空襲を避けるために田舎へ疎開していました。',
              jlpt: null,
              common: true,
            },
          ],
        },
        answer_synonyms: [
          {
            id: 3,
            character: '弾丸',
            kana: 'だんがん',
            review: 8657,
          },
        ],
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-12-22T04:24:15.445352Z',
        needs_review: true,
        unlock_date: '2016-12-22T04:24:15.444800Z',
        next_review_date: '2016-12-22T04:24:15.466896Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'enlighten',
        wanikani_srs_numeric: 8,
        wanikani_burned: false,
        notes: null,
        user: 1,
      },
      {
        id: 14,
        vocabulary: {
          meaning: 'demand',
          readings: [
            {
              character: '需要',
              kana: 'じゅよう',
              level: 38,
              tags: [
                'Noun',
              ],
              sentence_en: 'Imported cars are in strong demand.',
              sentence_ja: '輸入車の需要は強い',
              jlpt: 'JLPT N3',
              common: true,
            },
          ],
        },
        answer_synonyms: [
          {
            id: 3,
            character: '弾丸',
            kana: 'だんがん',
            review: 8657,
          },
        ],
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-12-22T04:24:15.585328Z',
        needs_review: true,
        unlock_date: '2016-12-22T04:24:15.584991Z',
        next_review_date: '2016-12-22T04:24:15.608861Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'master',
        wanikani_srs_numeric: 7,
        wanikani_burned: false,
        notes: null,
        user: 1,
      },
      {
        id: 15,
        vocabulary: {
          meaning: 'tendency',
          readings: [
            {
              character: '傾向',
              kana: 'けいこう',
              level: 38,
              tags: [
                'Noun',
                'Suru verb',
              ],
              sentence_en: "The world's population tends to increase.",
              sentence_ja: '世界の人口は増加する傾向にある',
              jlpt: 'JLPT N3',
              common: true,
            },
          ],
        },
        answer_synonyms: [],
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-12-22T04:24:15.679549Z',
        needs_review: true,
        unlock_date: '2016-12-22T04:24:15.679210Z',
        next_review_date: '2016-12-22T04:24:15.706178Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'enlighten',
        wanikani_srs_numeric: 8,
        wanikani_burned: false,
        notes: null,
        user: 1,
      },
      {
        id: 16,
        vocabulary: {
          meaning: 'to publish',
          readings: [
            {
              character: '出版する',
              kana: 'しゅっぱんする',
              level: 32,
              tags: [
                'Suru verb',
              ],
              sentence_en: 'Although he is a famous fiction writer, he sometimes self-publishes his books.',
              sentence_ja: '彼は有名な小説家だが、時々自費出版することもあるんだよ。',
              jlpt: null,
              common: null,
            },
            {
              character: '刊行する',
              kana: 'かんこうする',
              level: 38,
              tags: [
                'Suru verb',
              ],
              sentence_en: 'Mami asked Aya to publish a bacon magazine with her.',
              sentence_ja: 'マミはアヤに、ベーコン雑誌を一緒に刊行しないかと尋ねた。',
              jlpt: null,
              common: null,
            },
          ],
        },
        answer_synonyms: [],
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-12-22T04:24:15.770868Z',
        needs_review: true,
        unlock_date: '2016-12-22T04:24:15.770431Z',
        next_review_date: '2016-12-22T04:24:15.791888Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'enlighten',
        wanikani_srs_numeric: 8,
        wanikani_burned: false,
        notes: null,
        user: 1,
      },
      {
        id: 17,
        vocabulary: {
          meaning: 'deter, stave off',
          readings: [
            {
              character: '抑止',
              kana: 'よくし',
              level: 38,
              tags: [
                'Noun',
                'Suru verb',
              ],
              sentence_en: 'Which country do you think has the best crime prevention model?',
              sentence_ja: 'どの国が一番素晴らしい犯罪抑止モデルを有していると思われますか。',
              jlpt: null,
              common: true,
            },
          ],
        },
        answer_synonyms: [],
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-12-22T04:24:15.870313Z',
        needs_review: true,
        unlock_date: '2016-12-22T04:24:15.869931Z',
        next_review_date: '2016-12-22T04:24:15.887549Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'enlighten',
        wanikani_srs_numeric: 8,
        wanikani_burned: false,
        notes: null,
        user: 1,
      },
      {
        id: 18,
        vocabulary: {
          meaning: 'loose, mild, gentle',
          readings: [
            {
              character: '緩やか',
              kana: 'ゆるやか',
              level: 38,
              tags: [
                'Na adjective',
              ],
              sentence_en: 'From the castle we could see the whole curve of the river around its base.',
              sentence_ja: '城からそのふもとをゆるやかに湾曲して流れる川全体が見えました',
              jlpt: 'JLPT N1',
              common: true,
            },
          ],
        },
        answer_synonyms: [],
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-12-22T04:24:15.982779Z',
        needs_review: true,
        unlock_date: '2016-12-22T04:24:15.982392Z',
        next_review_date: '2016-12-22T04:24:16.004986Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'enlighten',
        wanikani_srs_numeric: 8,
        wanikani_burned: false,
        notes: null,
        user: 1,
      },
      {
        id: 19,
        vocabulary: {
          meaning: 'oppression',
          readings: [
            {
              character: '抑圧',
              kana: 'よくあつ',
              level: 38,
              tags: [
                'Noun',
                'Suru verb',
              ],
              sentence_en: 'He stood for those who were oppressed.',
              sentence_ja: '彼は抑圧されている者達の味方をした',
              jlpt: 'JLPT N1',
              common: true,
            },
          ],
        },
        answer_synonyms: [],
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-12-22T04:24:16.082235Z',
        needs_review: true,
        unlock_date: '2016-12-22T04:24:16.081596Z',
        next_review_date: '2016-12-22T04:24:16.108094Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'enlighten',
        wanikani_srs_numeric: 8,
        wanikani_burned: false,
        notes: null,
        user: 1,
      },
      {
        id: 20,
        vocabulary: {
          meaning: 'secret, confidential',
          readings: [
            {
              character: '内緒',
              kana: 'ないしょ',
              level: 38,
              tags: [
                'Noun',
                'No adjective',
              ],
              sentence_en: 'I went there in private.',
              sentence_ja: '私は内緒でそこへ行った',
              jlpt: null,
              common: true,
            },
          ],
        },
        answer_synonyms: [],
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-12-22T04:24:16.245956Z',
        needs_review: true,
        unlock_date: '2016-12-22T04:24:16.245676Z',
        next_review_date: '2016-12-22T04:24:16.264893Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'enlighten',
        wanikani_srs_numeric: 8,
        wanikani_burned: false,
        notes: null,
        user: 1,
      },
      {
        id: 21,
        vocabulary: {
          meaning: 'depiction',
          readings: [
            {
              character: '描写',
              kana: 'びょうしゃ',
              level: 38,
              tags: [
                'Noun',
                'Suru verb',
              ],
              sentence_en: "Dickens' thoughts come across along with the vivid depiction of old London.",
              sentence_ja: 'の考えがの下町の生き生きした描写と共に読者には伝わる',
              jlpt: 'JLPT N1',
              common: true,
            },
          ],
        },
        answer_synonyms: [],
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-12-22T04:24:16.402163Z',
        needs_review: true,
        unlock_date: '2016-12-22T04:24:16.401683Z',
        next_review_date: '2016-12-22T04:24:16.426623Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'enlighten',
        wanikani_srs_numeric: 8,
        wanikani_burned: false,
        notes: null,
        user: 1,
      },
      {
        id: 22,
        vocabulary: {
          meaning: 'bribe',
          readings: [
            {
              character: '賄賂',
              kana: 'わいろ',
              level: 38,
              tags: [
                'Noun',
              ],
              sentence_en: 'Did you or did you not accept the bribe?',
              sentence_ja: '賄賂を受け取ったのですかそれとも受け取らなかったのですか',
              jlpt: null,
              common: true,
            },
          ],
        },
        answer_synonyms: [],
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-12-22T04:24:16.542407Z',
        needs_review: true,
        unlock_date: '2016-12-22T04:24:16.541927Z',
        next_review_date: '2016-12-22T04:24:16.559635Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'enlighten',
        wanikani_srs_numeric: 8,
        wanikani_burned: false,
        notes: null,
        user: 1,
      },
      {
        id: 23,
        vocabulary: {
          meaning: 'return, restoration',
          readings: [
            {
              character: '返還',
              kana: 'へんかん',
              level: 38,
              tags: [
                'Noun',
                'Suru verb',
              ],
              sentence_en: 'I didn’t know that the championship flag had to be returned every year.',
              sentence_ja: '優勝旗が毎年返還されなくちゃいけないなんて、知らなかったよ。',
              jlpt: 'JLPT N1',
              common: true,
            },
          ],
        },
        answer_synonyms: [],
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-12-22T04:24:16.624895Z',
        needs_review: true,
        unlock_date: '2016-12-22T04:24:16.624160Z',
        next_review_date: '2016-12-22T04:24:16.641351Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'enlighten',
        wanikani_srs_numeric: 8,
        wanikani_burned: false,
        notes: null,
        user: 1,
      },
      {
        id: 24,
        vocabulary: {
          meaning: 'be entrusted with',
          readings: [
            {
              character: '受託',
              kana: 'じゅたく',
              level: 38,
              tags: [
                'Noun',
                'Suru verb',
              ],
              sentence_en: 'Any result obtained through the execution of the Commissioned Business shall belong to each party hereto.',
              sentence_ja: '乙が受託業務の実施により得た成果は甲乙双方に帰属するものとする',
              jlpt: null,
              common: true,
            },
          ],
        },
        answer_synonyms: [],
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-12-22T04:24:16.719987Z',
        needs_review: true,
        unlock_date: '2016-12-22T04:24:16.719559Z',
        next_review_date: '2016-12-22T04:24:16.738778Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'enlighten',
        wanikani_srs_numeric: 8,
        wanikani_burned: false,
        notes: null,
        user: 1,
      },
      {
        id: 25,
        vocabulary: {
          meaning: 'symmetry',
          readings: [
            {
              character: '対称',
              kana: 'たいしょう',
              level: 38,
              tags: [
                'Noun',
                'No adjective',
              ],
              sentence_en: 'The earth is not symmetrical about the equator.',
              sentence_ja: '地球は赤道に関して対称ではない',
              jlpt: null,
              common: true,
            },
          ],
        },
        answer_synonyms: [],
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-12-22T04:24:16.799294Z',
        needs_review: true,
        unlock_date: '2016-12-22T04:24:16.798617Z',
        next_review_date: '2016-12-22T04:24:16.816493Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'enlighten',
        wanikani_srs_numeric: 8,
        wanikani_burned: false,
        notes: null,
        user: 1,
      },
      {
        id: 26,
        vocabulary: {
          meaning: 'air conditioning',
          readings: [
            {
              character: '冷房',
              kana: 'れいぼう',
              level: 38,
              tags: [
                'Noun',
                'Suru verb',
              ],
              sentence_en: 'We measured the electricity used during air cooling in the same way as heating, and compared the old model air conditioner to the energy conservation (2001) model.',
              sentence_ja: '暖房と同様に冷房時の消費電力量を測定し旧型と省エネ型年製のエアコンを比較しました',
              jlpt: 'JLPT N4',
              common: true,
            },
          ],
        },
        answer_synonyms: [],
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-12-22T04:24:16.878188Z',
        needs_review: true,
        unlock_date: '2016-12-22T04:24:16.877760Z',
        next_review_date: '2016-12-22T04:24:16.906814Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'enlighten',
        wanikani_srs_numeric: 8,
        wanikani_burned: false,
        notes: null,
        user: 1,
      },
      {
        id: 27,
        vocabulary: {
          meaning: 'double play',
          readings: [
            {
              character: '併殺',
              kana: 'へいさつ',
              level: 38,
              tags: [
                'Noun',
                'Suru verb',
              ],
              sentence_en: '"Get two" is a Japanese word derived from English meaning double play.',
              sentence_ja: '「ゲッツー」というのは、併殺を意味する和製英語です。',
              jlpt: null,
              common: true,
            },
          ],
        },
        answer_synonyms: [],
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-12-22T04:24:17.008935Z',
        needs_review: true,
        unlock_date: '2016-12-22T04:24:17.008443Z',
        next_review_date: '2016-12-22T04:24:17.026846Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'enlighten',
        wanikani_srs_numeric: 8,
        wanikani_burned: false,
        notes: null,
        user: 1,
      },
      {
        id: 28,
        vocabulary: {
          meaning: 'musical performance, instrumental music',
          readings: [
            {
              character: '奏楽',
              kana: 'そうがく',
              level: 38,
              tags: [
                'Noun',
                'Suru verb',
              ],
              sentence_en: 'He belongs to the brass band.',
              sentence_ja: '彼は吹奏楽団に所属しています',
              jlpt: null,
              common: false,
            },
          ],
        },
        answer_synonyms: [],
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-12-22T04:24:17.094328Z',
        needs_review: true,
        unlock_date: '2016-12-22T04:24:17.093758Z',
        next_review_date: '2016-12-22T04:24:17.117328Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'master',
        wanikani_srs_numeric: 7,
        wanikani_burned: false,
        notes: null,
        user: 1,
      },
      {
        id: 29,
        vocabulary: {
          meaning: 'loose',
          readings: [
            {
              character: '緩い',
              kana: 'ゆるい',
              level: 38,
              tags: [
                'I adjective',
              ],
              sentence_en: 'These shoes are a little loose.',
              sentence_ja: 'この靴は少し緩い',
              jlpt: 'JLPT N2',
              common: true,
            },
          ],
        },
        answer_synonyms: [],
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-12-22T04:24:17.168459Z',
        needs_review: true,
        unlock_date: '2016-12-22T04:24:17.168109Z',
        next_review_date: '2016-12-22T04:24:17.182835Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'enlighten',
        wanikani_srs_numeric: 8,
        wanikani_burned: false,
        notes: null,
        user: 1,
      },
      {
        id: 30,
        vocabulary: {
          meaning: 'ordinary, normal, common',
          readings: [
            {
              character: '一般的',
              kana: 'いっぱんてき',
              level: 38,
              tags: [
                'Na adjective',
              ],
              sentence_en: 'Generally speaking, history repeats itself.',
              sentence_ja: '一般的にいえば歴史は繰り返す',
              jlpt: null,
              common: true,
            },
          ],
        },
        answer_synonyms: [],
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-12-22T04:24:17.257831Z',
        needs_review: true,
        unlock_date: '2016-12-22T04:24:17.257479Z',
        next_review_date: '2016-12-22T04:24:17.275090Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'enlighten',
        wanikani_srs_numeric: 8,
        wanikani_burned: false,
        notes: null,
        user: 1,
      },
      {
        id: 31,
        vocabulary: {
          meaning: 'to rely on, to trust, to depend on',
          readings: [
            {
              character: '頼る',
              kana: 'たよる',
              level: 38,
              tags: [
                'Intransitive verb',
                'Godan verb',
              ],
              sentence_en: 'Japan depends on foreign trade.',
              sentence_ja: '日本は貿易に頼っている',
              jlpt: 'JLPT N3',
              common: true,
            },
          ],
        },
        answer_synonyms: [],
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-12-22T04:24:17.403268Z',
        needs_review: true,
        unlock_date: '2016-12-22T04:24:17.402829Z',
        next_review_date: '2016-12-22T04:24:17.420802Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'enlighten',
        wanikani_srs_numeric: 8,
        wanikani_burned: false,
        notes: null,
        user: 1,
      },
      {
        id: 32,
        vocabulary: {
          meaning: 'tray',
          readings: [
            {
              character: '盤',
              kana: 'ばん',
              level: 38,
              tags: [
                'Noun',
                'Suffix',
              ],
              sentence_en: 'I’m collecting the Beatles’ vinyl records.',
              sentence_ja: '私はビートルズのビニール盤を収集しています。',
              jlpt: null,
              common: null,
            },
          ],
        },
        answer_synonyms: [],
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-12-22T04:24:17.499887Z',
        needs_review: true,
        unlock_date: '2016-12-22T04:24:17.499417Z',
        next_review_date: '2016-12-22T04:24:17.523934Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'enlighten',
        wanikani_srs_numeric: 8,
        wanikani_burned: false,
        notes: null,
        user: 1,
      },
      {
        id: 33,
        vocabulary: {
          meaning: 'to exceed, to go over, to surpass',
          readings: [
            {
              character: '超す',
              kana: 'こす',
              level: 38,
              tags: [
                'Godan verb',
              ],
              sentence_en: 'He’s not really the kind of person who talks about their own feelings, so he hid that he was excessively obsessed with me. ',
              sentence_ja: '彼はあまり自分の気持ちを言葉で表さない人なので、度を超す程私に執着していることを隠していました。',
              jlpt: null,
              common: null,
            },
          ],
        },
        answer_synonyms: [
          {
            id: 4,
            character: '弾丸',
            kana: 'ぶぶぶ',
            review: 33,
          },
        ],
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-12-22T04:24:17.589594Z',
        needs_review: true,
        unlock_date: '2016-12-22T04:24:17.589199Z',
        next_review_date: '2016-12-22T04:24:17.607100Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'master',
        wanikani_srs_numeric: 7,
        wanikani_burned: false,
        notes: null,
        user: 1,
      },
    ],
  },
};
