module.exports = {
  profiles: {
    name: 'duncantest10',
    review_count: 7,
    api_key: '5fa2d9c257dda131a54018f5c3f5ff90',
    api_valid: true,
    join_date: '2012-07-04',
    last_wanikani_sync_date: '2016-06-08T04:32:37.856081Z',
    level: 33,
    unlocked_levels: ['33'],
    follow_me: true,
    auto_advance_on_success: true,
    auto_expand_answer_on_success: true,
    auto_expand_answer_on_failure: true,
    only_review_burned: false,
    on_vacation: false,
    vacation_date: null,
  },
  messages: [],
  reviews: {
    count: 7,
    results: [
      {
        id: 5255,
        vocabulary: {
          meaning: 'happy birthday',
          readings: [
            {
              character: 'お誕生日おめでとう',
              kana: 'おたんじょうびおめでとう',
              level: 17,
              tags: [
                'Intransitive verb', 'Godan verb',
              ],
              sentence_en: 'She smoothly and elegantly poured the water into the glass.',
              sentence_ja: '滞りのない優雅な仕草でグラスに水を注ぎ込んだ',
              jlpt: 'JLPT N1',
              common: false,
            },
          ],
        },
        correct: 1,
        incorrect: 0,
        streak: 5,
        last_studied: '2016-09-24T04:17:25.128478Z',
        needs_review: true,
        unlock_date: '2016-09-17T01:17:04.682953Z',
        next_review_date: '2016-09-24T08:30:00.145429Z',
        burned: false,
        hidden: false,
        notes: null,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5256,
        vocabulary: {
          meaning: 'times (suffix)',
          readings: [
            {
              character: '〜回',
              kana: '〜かい',
              level: 17,
              tags: [
                'Noun', 'Suffix',
              ],
              sentence_en: 'Duck!',
              sentence_ja: '頭を下げろ',
              jlpt: null,
              common: true,
            },
          ],
        },
        correct: 1,
        incorrect: 0,
        streak: 7,
        last_studied: '2016-09-24T04:17:22.193801Z',
        needs_review: true,
        unlock_date: '2016-09-17T01:17:04.762030Z',
        next_review_date: '2016-09-24T08:30:00.209765Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5257,
        vocabulary: {
          meaning: 'diplomat',
          readings: [
            {
              character: '外交官',
              kana: 'がいこうかん',
              level: 17,
              tags: [
                'Intransitive verb', 'Godan verb',
              ],
              sentence_en: 'She smoothly and elegantly poured the water into the glass.',
              sentence_ja: '滞りのない優雅な仕草でグラスに水を注ぎ込んだ',
              jlpt: 'JLPT N1',
              common: false,
            },
          ],
        },
        correct: 1,
        incorrect: 0,
        streak: 6,
        last_studied: '2016-09-24T04:17:15.451267Z',
        needs_review: true,
        unlock_date: '2016-09-17T01:17:04.833940Z',
        next_review_date: '2016-09-24T08:30:00.478617Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5262,
        vocabulary: {
          meaning: 'hallucination',
          readings: [
            {
              character: '幻覚',
              kana: 'げんかく',
              level: 17,
              tags: [
                'Intransitive verb', 'Godan verb',
              ],
              sentence_en: 'She smoothly and elegantly poured the water into the glass.',
              sentence_ja: '滞りのない優雅な仕草でグラスに水を注ぎ込んだ',
              jlpt: 'JLPT N1',
              common: false,
            },
          ],
        },
        correct: 1,
        incorrect: 0,
        streak: 8,
        last_studied: '2016-09-24T04:03:48.772029Z',
        needs_review: true,
        unlock_date: '2016-09-17T01:17:05.102995Z',
        next_review_date: '2016-09-24T08:15:00.787795Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5266,
        vocabulary: {
          meaning: 'fruit',
          readings: [
            {
              character: '果物',
              kana: 'くだもの',
              level: 17,
              tags: [
                'Intransitive verb', 'Godan verb',
              ],
              sentence_en: 'She smoothly and elegantly poured the water into the glass.',
              sentence_ja: '滞りのない優雅な仕草でグラスに水を注ぎ込んだ',
              jlpt: 'JLPT N1',
              common: false,
            },
          ],
        },
        correct: 0,
        incorrect: 2,
        streak: 0,
        last_studied: '2016-09-24T04:07:35.274195Z',
        needs_review: true,
        unlock_date: '2016-09-17T01:17:05.365277Z',
        next_review_date: '2016-09-24T08:15:00.289917Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5268,
        vocabulary: {
          meaning: 'consciously, awareness, consciousness',
          readings: [
            {
              character: '意識',
              kana: 'いしき',
              level: 17,
              tags: [
                'Intransitive verb', 'Godan verb',
              ],
              sentence_en: 'She smoothly and elegantly poured the water into the glass.',
              sentence_ja: '滞りのない優雅な仕草でグラスに水を注ぎ込んだ',
              jlpt: 'JLPT N1',
              common: false,
            },
          ],
        },
        correct: 2,
        incorrect: 0,
        streak: 2,
        last_studied: '2016-11-08T05:55:47.575650Z',
        needs_review: true,
        unlock_date: '2016-09-17T01:17:05.471429Z',
        next_review_date: '2016-11-08T14:00:00.585663Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5269,
        vocabulary: {
          meaning: 'hypothesis',
          readings: [
            {
              character: '仮説',
              kana: 'かせつ',
              level: 17,
              tags: [
                'Intransitive verb', 'Godan verb',
              ],
              sentence_en: 'She smoothly and elegantly poured the water into the glass.',
              sentence_ja: '滞りのない優雅な仕草でグラスに水を注ぎ込んだ',
              jlpt: 'JLPT N1',
              common: false,
            },
          ],
        },
        correct: 1,
        incorrect: 0,
        streak: 1,
        last_studied: '2016-09-24T04:04:01.158027Z',
        needs_review: true,
        unlock_date: '2016-09-17T01:17:05.513865Z',
        next_review_date: '2016-09-24T08:15:00.170187Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5271,
        vocabulary: {
          meaning: 'both sides',
          readings: [
            {
              character: '両側',
              kana: 'りょうがわ',
              level: 17,
              tags: [
                'Intransitive verb', 'Godan verb',
              ],
              sentence_en: 'She smoothly and elegantly poured the water into the glass.',
              sentence_ja: '滞りのない優雅な仕草でグラスに水を注ぎ込んだ',
              jlpt: 'JLPT N1',
              common: false,
            },
          ],
        },
        correct: 0,
        incorrect: 1,
        streak: 0,
        last_studied: '2016-09-24T04:15:29.938034Z',
        needs_review: true,
        unlock_date: '2016-09-17T01:17:05.658677Z',
        next_review_date: '2016-09-24T08:30:00.958742Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5272,
        vocabulary: {
          meaning: 'absolutely, by all means',
          readings: [
            {
              character: '是非',
              kana: 'ぜひ',
              level: 17,
              tags: [
                'Intransitive verb', 'Godan verb',
              ],
              sentence_en: 'She smoothly and elegantly poured the water into the glass.',
              sentence_ja: '滞りのない優雅な仕草でグラスに水を注ぎ込んだ',
              jlpt: 'JLPT N1',
              common: false,
            },
          ],
        },
        correct: 1,
        incorrect: 4,
        streak: 1,
        last_studied: '2016-09-24T03:49:14.158194Z',
        needs_review: true,
        unlock_date: '2016-09-17T01:17:05.699788Z',
        next_review_date: '2016-09-24T08:00:00.169674Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5273,
        vocabulary: {
          meaning: 'absurd, rash, excessive',
          readings: [
            {
              character: '無茶',
              kana: 'むちゃ',
              level: 17,
              tags: [
                'Intransitive verb', 'Godan verb',
              ],
              sentence_en: 'She smoothly and elegantly poured the water into the glass.',
              sentence_ja: '滞りのない優雅な仕草でグラスに水を注ぎ込んだ',
              jlpt: 'JLPT N1',
              common: false,
            },
          ],
        },
        correct: 3,
        incorrect: 0,
        streak: 3,
        last_studied: '2016-09-24T03:49:19.389870Z',
        needs_review: true,
        unlock_date: '2016-09-17T01:17:05.809550Z',
        next_review_date: '2016-09-25T04:00:00.399751Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5275,
        vocabulary: {
          meaning: 'anonymous',
          readings: [
            {
              character: '無名',
              kana: 'むめい',
              level: 17,
              tags: [
                'Intransitive verb', 'Godan verb',
              ],
              sentence_en: 'She smoothly and elegantly poured the water into the glass.',
              sentence_ja: '滞りのない優雅な仕草でグラスに水を注ぎ込んだ',
              jlpt: 'JLPT N1',
              common: false,
            },
          ],
        },
        correct: 2,
        incorrect: 1,
        streak: 1,
        last_studied: '2016-09-24T03:59:43.869871Z',
        needs_review: true,
        unlock_date: '2016-09-17T01:17:05.898332Z',
        next_review_date: '2016-09-24T08:00:00.880710Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5276,
        vocabulary: {
          meaning: 'bottom',
          readings: [
            {
              character: '底',
              kana: 'そこ',
              level: 17,
              tags: [
                'Intransitive verb', 'Godan verb',
              ],
              sentence_en: 'She smoothly and elegantly poured the water into the glass.',
              sentence_ja: '滞りのない優雅な仕草でグラスに水を注ぎ込んだ',
              jlpt: 'JLPT N1',
              common: false,
            },
          ],
        },
        correct: 1,
        incorrect: 0,
        streak: 1,
        last_studied: '2016-09-24T04:14:40.511547Z',
        needs_review: true,
        unlock_date: '2016-09-17T01:17:05.970576Z',
        next_review_date: '2016-09-24T08:15:00.539487Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5280,
        vocabulary: {
          meaning: 'arms, weapons',
          readings: [
            {
              character: '兵器',
              kana: 'へいき',
              level: 17,
              tags: [
                'Intransitive verb', 'Godan verb',
              ],
              sentence_en: 'She smoothly and elegantly poured the water into the glass.',
              sentence_ja: '滞りのない優雅な仕草でグラスに水を注ぎ込んだ',
              jlpt: 'JLPT N1',
              common: false,
            },
          ],
        },
        correct: 2,
        incorrect: 1,
        streak: 2,
        last_studied: '2016-11-08T05:53:11.351039Z',
        needs_review: true,
        unlock_date: '2016-09-17T01:17:06.216368Z',
        next_review_date: '2016-11-08T14:00:00.367548Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5282,
        vocabulary: {
          meaning: 'fantasy, illusion',
          readings: [
            {
              character: '幻想',
              kana: 'げんそう',
              level: 17,
              tags: [
                'Intransitive verb', 'Godan verb',
              ],
              sentence_en: 'She smoothly and elegantly poured the water into the glass.',
              sentence_ja: '滞りのない優雅な仕草でグラスに水を注ぎ込んだ',
              jlpt: 'JLPT N1',
              common: false,
            },
          ],
        },
        correct: 1,
        incorrect: 0,
        streak: 1,
        last_studied: '2016-09-24T04:11:26.982438Z',
        needs_review: true,
        unlock_date: '2016-09-17T01:17:06.392457Z',
        next_review_date: '2016-09-24T08:15:00.991999Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5283,
        vocabulary: {
          meaning: 'explanation',
          readings: [
            {
              character: '説明',
              kana: 'せつめい',
              level: 17,
              tags: [
                'Intransitive verb', 'Godan verb',
              ],
              sentence_en: 'She smoothly and elegantly poured the water into the glass.',
              sentence_ja: '滞りのない優雅な仕草でグラスに水を注ぎ込んだ',
              jlpt: 'JLPT N1',
              common: false,
            },
          ],
        },
        correct: 1,
        incorrect: 1,
        streak: 1,
        last_studied: '2016-11-08T05:53:33.901233Z',
        needs_review: true,
        unlock_date: '2016-09-17T01:17:06.472232Z',
        next_review_date: '2016-11-08T10:00:00.914229Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5284,
        vocabulary: {
          meaning: 'glory',
          readings: [
            {
              character: '栄光',
              kana: 'えいこう',
              level: 17,
              tags: [
                'Intransitive verb', 'Godan verb',
              ],
              sentence_en: 'She smoothly and elegantly poured the water into the glass.',
              sentence_ja: '滞りのない優雅な仕草でグラスに水を注ぎ込んだ',
              jlpt: 'JLPT N1',
              common: false,
            },
          ],
        },
        correct: 0,
        incorrect: 2,
        streak: 0,
        last_studied: '2016-09-24T04:11:34.245302Z',
        needs_review: true,
        unlock_date: '2016-09-17T01:17:06.536739Z',
        next_review_date: '2016-09-24T08:15:00.255750Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5304,
        vocabulary: {
          meaning: 'ume, japanese plum',
          readings: [
            {
              character: '梅',
              kana: 'うめ',
              level: 17,
              tags: [
                'Intransitive verb', 'Godan verb',
              ],
              sentence_en: 'She smoothly and elegantly poured the water into the glass.',
              sentence_ja: '滞りのない優雅な仕草でグラスに水を注ぎ込んだ',
              jlpt: 'JLPT N1',
              common: false,
            },
          ],
        },
        correct: 0,
        incorrect: 2,
        streak: 0,
        last_studied: '2016-09-24T04:13:23.479983Z',
        needs_review: true,
        unlock_date: '2016-09-17T01:17:07.917487Z',
        next_review_date: '2016-09-24T08:15:00.490217Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5306,
        vocabulary: {
          meaning: 'aichi prefecture',
          readings: [
            {
              character: '愛知県',
              kana: 'あいちけん',
              level: 17,
              tags: [
                'Intransitive verb', 'Godan verb',
              ],
              sentence_en: 'She smoothly and elegantly poured the water into the glass.',
              sentence_ja: '滞りのない優雅な仕草でグラスに水を注ぎ込んだ',
              jlpt: 'JLPT N1',
              common: false,
            },
          ],
        },
        correct: 2,
        incorrect: 0,
        streak: 2,
        last_studied: '2016-09-24T03:49:17.499190Z',
        needs_review: true,
        unlock_date: '2016-09-17T01:17:08.056111Z',
        next_review_date: '2016-09-24T12:00:00.509094Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5308,
        vocabulary: {
          meaning: 'attendance',
          readings: [
            {
              character: '出席',
              kana: 'しゅっせき',
              level: 17,
              tags: [
                'Intransitive verb', 'Godan verb',
              ],
              sentence_en: 'She smoothly and elegantly poured the water into the glass.',
              sentence_ja: '滞りのない優雅な仕草でグラスに水を注ぎ込んだ',
              jlpt: 'JLPT N1',
              common: false,
            },
          ],
        },
        correct: 1,
        incorrect: 0,
        streak: 1,
        last_studied: '2016-09-24T04:02:03.826764Z',
        needs_review: true,
        unlock_date: '2016-09-17T01:17:08.186981Z',
        next_review_date: '2016-09-24T08:15:00.839601Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5310,
        vocabulary: {
          meaning: 'british person, english person',
          readings: [
            {
              character: 'イギリス人',
              kana: 'いぎりすじん',
              level: 17,
              tags: [
                'Noun', 'Suffix',
              ],
              sentence_en: 'Duck!',
              sentence_ja: '頭を下げろ',
              jlpt: null,
              common: true,
            }, {
              character: 'イギリス人',
              kana: 'イギリスじん',
              level: 17,
              tags: [
                'Intransitive verb', 'Godan verb',
              ],
              sentence_en: 'She smoothly and elegantly poured the water into the glass.',
              sentence_ja: '滞りのない優雅な仕草でグラスに水を注ぎ込んだ',
              jlpt: 'JLPT N1',
              common: false,
            },
          ],
        },
        correct: 0,
        incorrect: 1,
        streak: 0,
        last_studied: '2016-09-24T04:15:12.978475Z',
        needs_review: true,
        unlock_date: '2016-09-17T01:17:08.347694Z',
        next_review_date: '2016-09-24T08:30:00.991457Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5315,
        vocabulary: {
          meaning: 'after all, eventually, in the end',
          readings: [
            {
              character: '結局',
              kana: 'けっきょく',
              level: 17,
              tags: [
                'Intransitive verb', 'Godan verb',
              ],
              sentence_en: 'She smoothly and elegantly poured the water into the glass.',
              sentence_ja: '滞りのない優雅な仕草でグラスに水を注ぎ込んだ',
              jlpt: 'JLPT N1',
              common: false,
            },
          ],
        },
        correct: 2,
        incorrect: 0,
        streak: 2,
        last_studied: '2016-09-24T03:49:03.075360Z',
        needs_review: true,
        unlock_date: '2016-09-17T01:17:08.652826Z',
        next_review_date: '2016-09-24T12:00:00.101972Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5318,
        vocabulary: {
          meaning: 'atom',
          readings: [
            {
              character: '原子',
              kana: 'げんし',
              level: 17,
              tags: [
                'Intransitive verb', 'Godan verb',
              ],
              sentence_en: 'She smoothly and elegantly poured the water into the glass.',
              sentence_ja: '滞りのない優雅な仕草でグラスに水を注ぎ込んだ',
              jlpt: 'JLPT N1',
              common: false,
            },
          ],
        },
        correct: 1,
        incorrect: 0,
        streak: 1,
        last_studied: '2016-09-24T04:01:26.278920Z',
        needs_review: true,
        unlock_date: '2016-09-17T01:17:08.895078Z',
        next_review_date: '2016-09-24T08:15:00.306290Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5324,
        vocabulary: {
          meaning: 'absence, nonattendance',
          readings: [
            {
              character: '欠席',
              kana: 'けっせき',
              level: 17,
              tags: [
                'Intransitive verb', 'Godan verb',
              ],
              sentence_en: 'She smoothly and elegantly poured the water into the glass.',
              sentence_ja: '滞りのない優雅な仕草でグラスに水を注ぎ込んだ',
              jlpt: 'JLPT N1',
              common: false,
            },
          ],
        },
        correct: 1,
        incorrect: 6,
        streak: 1,
        last_studied: '2016-09-24T04:00:01.423616Z',
        needs_review: true,
        unlock_date: '2016-09-17T01:17:09.306385Z',
        next_review_date: '2016-09-24T08:15:00.453473Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5326,
        vocabulary: {
          meaning: 'honor, privilege, honour',
          readings: [
            {
              character: '光栄',
              kana: 'こうえい',
              level: 17,
              tags: [
                'Intransitive verb', 'Godan verb',
              ],
              sentence_en: 'She smoothly and elegantly poured the water into the glass.',
              sentence_ja: '滞りのない優雅な仕草でグラスに水を注ぎ込んだ',
              jlpt: 'JLPT N1',
              common: false,
            },
          ],
        },
        correct: 0,
        incorrect: 2,
        streak: 0,
        last_studied: '2016-09-24T04:04:06.185731Z',
        needs_review: true,
        unlock_date: '2016-09-17T01:17:09.500581Z',
        next_review_date: '2016-09-24T08:15:00.213606Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5331,
        vocabulary: {
          meaning: 'cause, origin, source',
          readings: [
            {
              character: '原因',
              kana: 'げんいん',
              level: 17,
              tags: [
                'Intransitive verb', 'Godan verb',
              ],
              sentence_en: 'She smoothly and elegantly poured the water into the glass.',
              sentence_ja: '滞りのない優雅な仕草でグラスに水を注ぎ込んだ',
              jlpt: 'JLPT N1',
              common: false,
            },
          ],
        },
        correct: 0,
        incorrect: 1,
        streak: 0,
        last_studied: '2016-09-24T04:00:57.360978Z',
        needs_review: true,
        unlock_date: '2016-09-17T01:17:09.824807Z',
        next_review_date: '2016-09-24T08:15:00.375730Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5339,
        vocabulary: {
          meaning: 'illusion, phantom',
          readings: [
            {
              character: '幻',
              kana: 'まぼろし',
              level: 17,
              tags: [
                'Intransitive verb', 'Godan verb',
              ],
              sentence_en: 'She smoothly and elegantly poured the water into the glass.',
              sentence_ja: '滞りのない優雅な仕草でグラスに水を注ぎ込んだ',
              jlpt: 'JLPT N1',
              common: false,
            },
          ],
        },
        correct: 1,
        incorrect: 0,
        streak: 1,
        last_studied: '2016-09-24T04:03:01.836120Z',
        needs_review: true,
        unlock_date: '2016-09-17T01:17:10.437718Z',
        next_review_date: '2016-09-24T08:15:00.845631Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5340,
        vocabulary: {
          meaning: 'bottom of one\'s heart, bottom of my heart',
          readings: [
            {
              character: '心底',
              kana: 'しんそこ',
              level: 17,
              tags: [
                'Intransitive verb', 'Godan verb',
              ],
              sentence_en: 'She smoothly and elegantly poured the water into the glass.',
              sentence_ja: '滞りのない優雅な仕草でグラスに水を注ぎ込んだ',
              jlpt: 'JLPT N1',
              common: false,
            },
          ],
        },
        correct: 0,
        incorrect: 1,
        streak: 0,
        last_studied: '2016-09-24T04:15:18.699689Z',
        needs_review: true,
        unlock_date: '2016-09-17T01:17:10.491852Z',
        next_review_date: '2016-09-24T08:30:00.711333Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5342,
        vocabulary: {
          meaning: 'building',
          readings: [
            {
              character: '建物',
              kana: 'たてもの',
              level: 17,
              tags: [
                'Intransitive verb', 'Godan verb',
              ],
              sentence_en: 'She smoothly and elegantly poured the water into the glass.',
              sentence_ja: '滞りのない優雅な仕草でグラスに水を注ぎ込んだ',
              jlpt: 'JLPT N1',
              common: false,
            },
          ],
        },
        correct: 0,
        incorrect: 1,
        streak: 0,
        last_studied: '2016-09-24T04:15:26.269826Z',
        needs_review: true,
        unlock_date: '2016-09-17T01:17:10.601355Z',
        next_review_date: '2016-09-24T08:30:00.288431Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5345,
        vocabulary: {
          meaning: 'failure, mistake',
          readings: [
            {
              character: '失敗',
              kana: 'しっぱい',
              level: 17,
              tags: [
                'Intransitive verb', 'Godan verb',
              ],
              sentence_en: 'She smoothly and elegantly poured the water into the glass.',
              sentence_ja: '滞りのない優雅な仕草でグラスに水を注ぎ込んだ',
              jlpt: 'JLPT N1',
              common: false,
            },
          ],
        },
        correct: 1,
        incorrect: 0,
        streak: 1,
        last_studied: '2016-09-24T04:04:38.330455Z',
        needs_review: true,
        unlock_date: '2016-09-17T01:17:10.775871Z',
        next_review_date: '2016-09-24T08:15:00.342518Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5349,
        vocabulary: {
          meaning: 'free, without charge',
          readings: [
            {
              character: '無料',
              kana: 'むりょう',
              level: 17,
              tags: [
                'Intransitive verb', 'Godan verb',
              ],
              sentence_en: 'She smoothly and elegantly poured the water into the glass.',
              sentence_ja: '滞りのない優雅な仕草でグラスに水を注ぎ込んだ',
              jlpt: 'JLPT N1',
              common: false,
            },
          ],
        },
        correct: 0,
        incorrect: 2,
        streak: 0,
        last_studied: '2016-09-24T04:04:40.679493Z',
        needs_review: true,
        unlock_date: '2016-09-17T01:17:11.017641Z',
        next_review_date: '2016-09-24T08:15:00.690664Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5350,
        vocabulary: {
          meaning: 'before christ, bc, bce, before common era',
          readings: [
            {
              character: '紀元前',
              kana: 'きげんぜん',
              level: 17,
              tags: [
                'Intransitive verb', 'Godan verb',
              ],
              sentence_en: 'She smoothly and elegantly poured the water into the glass.',
              sentence_ja: '滞りのない優雅な仕草でグラスに水を注ぎ込んだ',
              jlpt: 'JLPT N1',
              common: false,
            },
          ],
        },
        correct: 1,
        incorrect: 0,
        streak: 1,
        last_studied: '2016-09-24T04:15:01.483725Z',
        needs_review: true,
        unlock_date: '2016-09-17T01:17:11.092475Z',
        next_review_date: '2016-09-24T08:30:00.511219Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5353,
        vocabulary: {
          meaning: 'vanity',
          readings: [
            {
              character: '虚栄心',
              kana: 'きょえいしん',
              level: 17,
              tags: [
                'Intransitive verb', 'Godan verb',
              ],
              sentence_en: 'She smoothly and elegantly poured the water into the glass.',
              sentence_ja: '滞りのない優雅な仕草でグラスに水を注ぎ込んだ',
              jlpt: 'JLPT N1',
              common: false,
            },
          ],
        },
        correct: 1,
        incorrect: 1,
        streak: 0,
        last_studied: '2016-09-24T04:13:20.924045Z',
        needs_review: true,
        unlock_date: '2016-09-17T01:17:11.302245Z',
        next_review_date: '2016-09-24T08:15:00.934686Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5354,
        vocabulary: {
          meaning: 'consciousness, awareness, realization',
          readings: [
            {
              character: '自覚',
              kana: 'じかく',
              level: 17,
              tags: [
                'Intransitive verb', 'Godan verb',
              ],
              sentence_en: 'She smoothly and elegantly poured the water into the glass.',
              sentence_ja: '滞りのない優雅な仕草でグラスに水を注ぎ込んだ',
              jlpt: 'JLPT N1',
              common: false,
            },
          ],
        },
        correct: 1,
        incorrect: 0,
        streak: 1,
        last_studied: '2016-09-24T04:01:10.193845Z',
        needs_review: true,
        unlock_date: '2016-09-17T01:17:11.344745Z',
        next_review_date: '2016-09-24T08:15:00.214816Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5355,
        vocabulary: {
          meaning: 'illustration, explanatory diagram',
          readings: [
            {
              character: '図説',
              kana: 'ずせつ',
              level: 17,
              tags: [
                'Intransitive verb', 'Godan verb',
              ],
              sentence_en: 'She smoothly and elegantly poured the water into the glass.',
              sentence_ja: '滞りのない優雅な仕草でグラスに水を注ぎ込んだ',
              jlpt: 'JLPT N1',
              common: false,
            },
          ],
        },
        correct: 1,
        incorrect: 2,
        streak: 0,
        last_studied: '2016-11-08T06:00:36.318147Z',
        needs_review: true,
        unlock_date: '2016-09-17T01:17:11.429357Z',
        next_review_date: '2016-11-08T10:15:00.334043Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5356,
        vocabulary: {
          meaning: 'breakfast',
          readings: [
            {
              character: '朝ごはん',
              kana: 'あさごはん',
              level: 8,
              tags: [
                'Noun', 'Suffix',
              ],
              sentence_en: 'Duck!',
              sentence_ja: '頭を下げろ',
              jlpt: null,
              common: true,
            }, {
              character: '朝ご飯',
              kana: 'あさごはん',
              level: 17,
              tags: [
                'Intransitive verb', 'Godan verb',
              ],
              sentence_en: 'She smoothly and elegantly poured the water into the glass.',
              sentence_ja: '滞りのない優雅な仕草でグラスに水を注ぎ込んだ',
              jlpt: 'JLPT N1',
              common: false,
            },
          ],
        },
        correct: 0,
        incorrect: 1,
        streak: 0,
        last_studied: '2016-09-24T04:15:15.441257Z',
        needs_review: true,
        unlock_date: '2016-09-17T01:17:11.530983Z',
        next_review_date: '2016-09-24T08:30:00.452846Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5358,
        vocabulary: {
          meaning: 'bad tasting, unappetizing, unskillful',
          readings: [
            {
              character: '不味い',
              kana: 'まずい',
              level: 17,
              tags: [
                'Intransitive verb', 'Godan verb',
              ],
              sentence_en: 'She smoothly and elegantly poured the water into the glass.',
              sentence_ja: '滞りのない優雅な仕草でグラスに水を注ぎ込んだ',
              jlpt: 'JLPT N1',
              common: false,
            },
          ],
        },
        correct: 2,
        incorrect: 0,
        streak: 2,
        last_studied: '2016-11-08T05:54:50.108392Z',
        needs_review: true,
        unlock_date: '2016-09-17T01:17:11.662235Z',
        next_review_date: '2016-11-08T14:00:00.120521Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5362,
        vocabulary: {
          meaning: 'dinner, supper',
          readings: [
            {
              character: '晩ご飯',
              kana: 'ばんごはん',
              level: 17,
              tags: [
                'Intransitive verb', 'Godan verb',
              ],
              sentence_en: 'She smoothly and elegantly poured the water into the glass.',
              sentence_ja: '滞りのない優雅な仕草でグラスに水を注ぎ込んだ',
              jlpt: 'JLPT N1',
              common: false,
            },
          ],
        },
        correct: 1,
        incorrect: 1,
        streak: 0,
        last_studied: '2016-11-08T06:00:09.316833Z',
        needs_review: true,
        unlock_date: '2016-09-17T01:17:11.913170Z',
        next_review_date: '2016-11-08T10:15:00.329437Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5374,
        vocabulary: {
          meaning: 'to perform, to play',
          readings: [
            {
              character: '演ずる',
              kana: 'えんずる',
              level: 23,
              tags: [
                'Noun', 'Suffix',
              ],
              sentence_en: 'Duck!',
              sentence_ja: '頭を下げろ',
              jlpt: null,
              common: true,
            },
          ],
        },
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-11-01T06:22:28.946454Z',
        needs_review: true,
        unlock_date: '2016-11-01T06:22:28.946079Z',
        next_review_date: '2016-11-01T06:22:28.966779Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5375,
        vocabulary: {
          meaning: 'cape, small peninsula',
          readings: [
            {
              character: '崎',
              kana: 'さき',
              level: 23,
              tags: [
                'Noun', 'Suffix',
              ],
              sentence_en: 'Duck!',
              sentence_ja: '頭を下げろ',
              jlpt: null,
              common: true,
            },
          ],
        },
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-11-01T06:22:29.041604Z',
        needs_review: true,
        unlock_date: '2016-11-01T06:22:29.041272Z',
        next_review_date: '2016-11-01T06:22:29.057203Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5376,
        vocabulary: {
          meaning: 'milk, cow\'s milk',
          readings: [
            {
              character: '牛乳',
              kana: 'ぎゅうにゅう',
              level: 23,
              tags: [
                'Noun', 'Suffix',
              ],
              sentence_en: 'Duck!',
              sentence_ja: '頭を下げろ',
              jlpt: null,
              common: true,
            },
          ],
        },
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-11-01T06:22:29.127293Z',
        needs_review: true,
        unlock_date: '2016-11-01T06:22:29.126980Z',
        next_review_date: '2016-11-01T06:22:29.152805Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5377,
        vocabulary: {
          meaning: 'to call, to call out',
          readings: [
            {
              character: '呼ぶ',
              kana: 'よぶ',
              level: 23,
              tags: [
                'Noun', 'Suffix',
              ],
              sentence_en: 'Duck!',
              sentence_ja: '頭を下げろ',
              jlpt: null,
              common: true,
            },
          ],
        },
        correct: 1,
        incorrect: 0,
        streak: 1,
        last_studied: '2016-11-08T05:56:48.018895Z',
        needs_review: true,
        unlock_date: '2016-11-01T06:22:29.208650Z',
        next_review_date: '2016-11-08T10:00:00.040566Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5380,
        vocabulary: {
          meaning: 'extravagant',
          readings: [
            {
              character: '贅沢',
              kana: 'ぜいたく',
              level: 23,
              tags: [
                'Noun', 'Suffix',
              ],
              sentence_en: 'Duck!',
              sentence_ja: '頭を下げろ',
              jlpt: null,
              common: true,
            },
          ],
        },
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-11-01T06:22:29.403068Z',
        needs_review: true,
        unlock_date: '2016-11-01T06:22:29.402615Z',
        next_review_date: '2016-11-01T06:22:29.412470Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5381,
        vocabulary: {
          meaning: 'stoppage, suspension',
          readings: [
            {
              character: '停止',
              kana: 'ていし',
              level: 23,
              tags: [
                'Noun', 'Suffix',
              ],
              sentence_en: 'Duck!',
              sentence_ja: '頭を下げろ',
              jlpt: null,
              common: true,
            },
          ],
        },
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-11-01T06:22:29.448836Z',
        needs_review: true,
        unlock_date: '2016-11-01T06:22:29.448527Z',
        next_review_date: '2016-11-01T06:22:29.458327Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5383,
        vocabulary: {
          meaning: 'doctor',
          readings: [
            {
              character: '医者',
              kana: 'いしゃ',
              level: 8,
              tags: [
                'Noun', 'Suffix',
              ],
              sentence_en: 'Duck!',
              sentence_ja: '頭を下げろ',
              jlpt: null,
              common: true,
            }, {
              character: '医師',
              kana: 'いし',
              level: 23,
              tags: [
                'Noun', 'Suffix',
              ],
              sentence_en: 'Duck!',
              sentence_ja: '頭を下げろ',
              jlpt: null,
              common: true,
            },
          ],
        },
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-11-01T06:22:29.633832Z',
        needs_review: true,
        unlock_date: '2016-11-01T06:22:29.633411Z',
        next_review_date: '2016-11-01T06:22:29.652137Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5384,
        vocabulary: {
          meaning: 'rule, regulation',
          readings: [
            {
              character: '規則',
              kana: 'きそく',
              level: 23,
              tags: [
                'Noun', 'Suffix',
              ],
              sentence_en: 'Duck!',
              sentence_ja: '頭を下げろ',
              jlpt: null,
              common: true,
            },
          ],
        },
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-11-01T06:22:29.732527Z',
        needs_review: true,
        unlock_date: '2016-11-01T06:22:29.732180Z',
        next_review_date: '2016-11-01T06:22:29.751715Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5385,
        vocabulary: {
          meaning: 'championship, victory',
          readings: [
            {
              character: '優勝',
              kana: 'ゆうしょう',
              level: 23,
              tags: [
                'Noun', 'Suffix',
              ],
              sentence_en: 'Duck!',
              sentence_ja: '頭を下げろ',
              jlpt: null,
              common: true,
            },
          ],
        },
        correct: 1,
        incorrect: 0,
        streak: 1,
        last_studied: '2016-11-08T05:54:22.770952Z',
        needs_review: true,
        unlock_date: '2016-11-01T06:22:29.825453Z',
        next_review_date: '2016-11-08T10:00:00.781295Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5386,
        vocabulary: {
          meaning: 'home, house',
          readings: [
            {
              character: '家',
              kana: 'いえ',
              level: 7,
              tags: [
                'Noun', 'Suffix',
              ],
              sentence_en: 'Duck!',
              sentence_ja: '頭を下げろ',
              jlpt: null,
              common: true,
            }, {
              character: '家',
              kana: 'うち',
              level: 7,
              tags: [
                'Noun', 'Suffix',
              ],
              sentence_en: 'Duck!',
              sentence_ja: '頭を下げろ',
              jlpt: null,
              common: true,
            }, {
              character: '宅',
              kana: 'たく',
              level: 23,
              tags: [
                'Noun', 'Suffix',
              ],
              sentence_en: 'Duck!',
              sentence_ja: '頭を下げろ',
              jlpt: null,
              common: true,
            },
          ],
        },
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-11-01T06:22:29.909966Z',
        needs_review: true,
        unlock_date: '2016-11-01T06:22:29.909648Z',
        next_review_date: '2016-11-01T06:22:29.925097Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5387,
        vocabulary: {
          meaning: 'unemployment',
          readings: [
            {
              character: '無職',
              kana: 'むしょく',
              level: 23,
              tags: [
                'Noun', 'Suffix',
              ],
              sentence_en: 'Duck!',
              sentence_ja: '頭を下げろ',
              jlpt: null,
              common: true,
            },
          ],
        },
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-11-01T06:22:29.979563Z',
        needs_review: true,
        unlock_date: '2016-11-01T06:22:29.979206Z',
        next_review_date: '2016-11-01T06:22:30.007957Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5388,
        vocabulary: {
          meaning: 'tree trunk',
          readings: [
            {
              character: '幹',
              kana: 'みき',
              level: 23,
              tags: [
                'Noun', 'Suffix',
              ],
              sentence_en: 'Duck!',
              sentence_ja: '頭を下げろ',
              jlpt: null,
              common: true,
            },
          ],
        },
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-11-01T06:22:30.076151Z',
        needs_review: true,
        unlock_date: '2016-11-01T06:22:30.075839Z',
        next_review_date: '2016-11-01T06:22:30.094812Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5389,
        vocabulary: {
          meaning: 'one\'s home, one\'s own home',
          readings: [
            {
              character: '自宅',
              kana: 'じたく',
              level: 23,
              tags: [
                'Noun', 'Suffix',
              ],
              sentence_en: 'Duck!',
              sentence_ja: '頭を下げろ',
              jlpt: null,
              common: true,
            },
          ],
        },
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-11-01T06:22:30.173248Z',
        needs_review: true,
        unlock_date: '2016-11-01T06:22:30.172896Z',
        next_review_date: '2016-11-01T06:22:30.191215Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5390,
        vocabulary: {
          meaning: 'to raise, to elevate, to bring up',
          readings: [
            {
              character: '挙げる',
              kana: 'あげる',
              level: 23,
              tags: [
                'Noun', 'Suffix',
              ],
              sentence_en: 'Duck!',
              sentence_ja: '頭を下げろ',
              jlpt: null,
              common: true,
            },
          ],
        },
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-11-01T06:22:30.247711Z',
        needs_review: true,
        unlock_date: '2016-11-01T06:22:30.247394Z',
        next_review_date: '2016-11-01T06:22:30.265029Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5391,
        vocabulary: {
          meaning: 'to criticize, to criticise',
          readings: [
            {
              character: '批判する',
              kana: 'ひはんする',
              level: 23,
              tags: [
                'Noun', 'Suffix',
              ],
              sentence_en: 'Duck!',
              sentence_ja: '頭を下げろ',
              jlpt: null,
              common: true,
            }, {
              character: '非難する',
              kana: 'ひなんする',
              level: 22,
            },
          ],
        },
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-11-01T06:22:30.342169Z',
        needs_review: true,
        unlock_date: '2016-11-01T06:22:30.341591Z',
        next_review_date: '2016-11-01T06:22:30.363677Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5392,
        vocabulary: {
          meaning: 'economics, study of economics',
          readings: [
            {
              character: '経済学',
              kana: 'けいざいがく',
              level: 23,
              tags: [
                'Noun', 'Suffix',
              ],
              sentence_en: 'Duck!',
              sentence_ja: '頭を下げろ',
              jlpt: null,
              common: true,
            },
          ],
        },
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-11-01T06:22:30.422973Z',
        needs_review: true,
        unlock_date: '2016-11-01T06:22:30.422615Z',
        next_review_date: '2016-11-01T06:22:30.441967Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5393,
        vocabulary: {
          meaning: 'comprehension, understanding, roger',
          readings: [
            {
              character: '了解',
              kana: 'りょうかい',
              level: 23,
              tags: [
                'Noun', 'Suffix',
              ],
              sentence_en: 'Duck!',
              sentence_ja: '頭を下げろ',
              jlpt: null,
              common: true,
            },
          ],
        },
        correct: 1,
        incorrect: 0,
        streak: 1,
        last_studied: '2016-11-08T05:53:05.334719Z',
        needs_review: true,
        unlock_date: '2016-11-01T06:22:30.509110Z',
        next_review_date: '2016-11-08T10:00:00.349959Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5394,
        vocabulary: {
          meaning: 'receipt',
          readings: [
            {
              character: '領収書',
              kana: 'りょうしゅうしょ',
              level: 23,
              tags: [
                'Noun', 'Suffix',
              ],
              sentence_en: 'Duck!',
              sentence_ja: '頭を下げろ',
              jlpt: null,
              common: true,
            },
          ],
        },
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-11-01T06:22:30.591958Z',
        needs_review: true,
        unlock_date: '2016-11-01T06:22:30.591638Z',
        next_review_date: '2016-11-01T06:22:30.601330Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5396,
        vocabulary: {
          meaning: 'actor',
          readings: [
            {
              character: '俳優',
              kana: 'はいゆう',
              level: 23,
              tags: [
                'Noun', 'Suffix',
              ],
              sentence_en: 'Duck!',
              sentence_ja: '頭を下げろ',
              jlpt: null,
              common: true,
            }, {
              character: '男優',
              kana: 'だんゆう',
              level: 23,
              tags: [
                'Noun', 'Suffix',
              ],
              sentence_en: 'Duck!',
              sentence_ja: '頭を下げろ',
              jlpt: null,
              common: true,
            },
          ],
        },
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-11-01T06:22:30.733109Z',
        needs_review: true,
        unlock_date: '2016-11-01T06:22:30.732788Z',
        next_review_date: '2016-11-01T06:22:30.757565Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5397,
        vocabulary: {
          meaning: 'attorney, lawyer',
          readings: [
            {
              character: '弁護士',
              kana: 'べんごし',
              level: 23,
              tags: [
                'Noun', 'Suffix',
              ],
              sentence_en: 'Duck!',
              sentence_ja: '頭を下げろ',
              jlpt: null,
              common: true,
            },
          ],
        },
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-11-01T06:22:30.828317Z',
        needs_review: true,
        unlock_date: '2016-11-01T06:22:30.828004Z',
        next_review_date: '2016-11-01T06:22:30.851300Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5398,
        vocabulary: {
          meaning: 'bus stop',
          readings: [
            {
              character: 'バス停',
              kana: 'ばすてい',
              level: 23,
              tags: [
                'Noun', 'Suffix',
              ],
              sentence_en: 'Duck!',
              sentence_ja: '頭を下げろ',
              jlpt: null,
              common: true,
            }, {
              character: 'バス停',
              kana: 'バスてい',
              level: 23,
              tags: [
                'Noun', 'Suffix',
              ],
              sentence_en: 'Duck!',
              sentence_ja: '頭を下げろ',
              jlpt: null,
              common: true,
            },
          ],
        },
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-11-01T06:22:30.944961Z',
        needs_review: true,
        unlock_date: '2016-11-01T06:22:30.944628Z',
        next_review_date: '2016-11-01T06:22:30.957149Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5399,
        vocabulary: {
          meaning: 'standard, a standard',
          readings: [
            {
              character: '基準',
              kana: 'きじゅん',
              level: 23,
              tags: [
                'Noun', 'Suffix',
              ],
              sentence_en: 'Duck!',
              sentence_ja: '頭を下げろ',
              jlpt: null,
              common: true,
            },
          ],
        },
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-11-01T06:22:31.009229Z',
        needs_review: true,
        unlock_date: '2016-11-01T06:22:31.008918Z',
        next_review_date: '2016-11-01T06:22:31.018375Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5400,
        vocabulary: {
          meaning: 'law',
          readings: [
            {
              character: '法律',
              kana: 'ほうりつ',
              level: 23,
              tags: [
                'Noun', 'Suffix',
              ],
              sentence_en: 'Duck!',
              sentence_ja: '頭を下げろ',
              jlpt: null,
              common: true,
            },
          ],
        },
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-11-01T06:22:31.127911Z',
        needs_review: true,
        unlock_date: '2016-11-01T06:22:31.127600Z',
        next_review_date: '2016-11-01T06:22:31.142431Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5401,
        vocabulary: {
          meaning: 'haiku',
          readings: [
            {
              character: '俳句',
              kana: 'はいく',
              level: 23,
              tags: [
                'Noun', 'Suffix',
              ],
              sentence_en: 'Duck!',
              sentence_ja: '頭を下げろ',
              jlpt: null,
              common: true,
            },
          ],
        },
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-11-01T06:22:31.216953Z',
        needs_review: true,
        unlock_date: '2016-11-01T06:22:31.216594Z',
        next_review_date: '2016-11-01T06:22:31.234604Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5402,
        vocabulary: {
          meaning: 'income',
          readings: [
            {
              character: '収入',
              kana: 'しゅうにゅう',
              level: 23,
              tags: [
                'Noun', 'Suffix',
              ],
              sentence_en: 'Duck!',
              sentence_ja: '頭を下げろ',
              jlpt: null,
              common: true,
            },
          ],
        },
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-11-01T06:22:31.285150Z',
        needs_review: true,
        unlock_date: '2016-11-01T06:22:31.284828Z',
        next_review_date: '2016-11-01T06:22:31.294506Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5403,
        vocabulary: {
          meaning: 'job hunting',
          readings: [
            {
              character: '求職',
              kana: 'きゅうしょく',
              level: 23,
              tags: [
                'Noun', 'Suffix',
              ],
              sentence_en: 'Duck!',
              sentence_ja: '頭を下げろ',
              jlpt: null,
              common: true,
            },
          ],
        },
        correct: 0,
        incorrect: 1,
        streak: 0,
        last_studied: '2016-11-08T05:58:56.190368Z',
        needs_review: true,
        unlock_date: '2016-11-01T06:22:31.356471Z',
        next_review_date: '2016-11-08T10:00:00.200642Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5404,
        vocabulary: {
          meaning: 'kawasaki, kawasaki city',
          readings: [
            {
              character: '川崎',
              kana: 'かわさき',
              level: 23,
              tags: [
                'Noun', 'Suffix',
              ],
              sentence_en: 'Duck!',
              sentence_ja: '頭を下げろ',
              jlpt: null,
              common: true,
            },
          ],
        },
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-11-01T06:22:31.487570Z',
        needs_review: true,
        unlock_date: '2016-11-01T06:22:31.487172Z',
        next_review_date: '2016-11-01T06:22:31.500795Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5405,
        vocabulary: {
          meaning: 'local train',
          readings: [
            {
              character: '各駅停車',
              kana: 'かくえきていしゃ',
              level: 23,
              tags: [
                'Noun', 'Suffix',
              ],
              sentence_en: 'Duck!',
              sentence_ja: '頭を下げろ',
              jlpt: null,
              common: true,
            },
          ],
        },
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-11-01T06:22:31.570447Z',
        needs_review: true,
        unlock_date: '2016-11-01T06:22:31.570045Z',
        next_review_date: '2016-11-01T06:22:31.593318Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5406,
        vocabulary: {
          meaning: 'nagasaki',
          readings: [
            {
              character: '長崎',
              kana: 'ながさき',
              level: 23,
              tags: [
                'Noun', 'Suffix',
              ],
              sentence_en: 'Duck!',
              sentence_ja: '頭を下げろ',
              jlpt: null,
              common: true,
            },
          ],
        },
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-11-01T06:22:31.643132Z',
        needs_review: true,
        unlock_date: '2016-11-01T06:22:31.642821Z',
        next_review_date: '2016-11-01T06:22:31.651512Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5408,
        vocabulary: {
          meaning: 'to judge',
          readings: [
            {
              character: '判断する',
              kana: 'はんだんする',
              level: 23,
              tags: [
                'Noun', 'Suffix',
              ],
              sentence_en: 'Duck!',
              sentence_ja: '頭を下げろ',
              jlpt: null,
              common: true,
            }, {
              character: '裁く',
              kana: 'さばく',
              level: 23,
              tags: [
                'Noun', 'Suffix',
              ],
              sentence_en: 'Duck!',
              sentence_ja: '頭を下げろ',
              jlpt: null,
              common: true,
            },
          ],
        },
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-11-01T06:22:31.808493Z',
        needs_review: true,
        unlock_date: '2016-11-01T06:22:31.808143Z',
        next_review_date: '2016-11-01T06:22:31.817847Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5410,
        vocabulary: {
          meaning: 'sense of responsibility',
          readings: [
            {
              character: '責任感',
              kana: 'せきにんかん',
              level: 23,
              tags: [
                'Noun', 'Suffix',
              ],
              sentence_en: 'Duck!',
              sentence_ja: '頭を下げろ',
              jlpt: null,
              common: true,
            },
          ],
        },
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-11-01T06:22:31.939710Z',
        needs_review: true,
        unlock_date: '2016-11-01T06:22:31.939383Z',
        next_review_date: '2016-11-01T06:22:31.956665Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5411,
        vocabulary: {
          meaning: 'to confirm, to verify',
          readings: [
            {
              character: '確認する',
              kana: 'かくにんする',
              level: 23,
              tags: [
                'Noun', 'Suffix',
              ],
              sentence_en: 'Duck!',
              sentence_ja: '頭を下げろ',
              jlpt: null,
              common: true,
            },
          ],
        },
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-11-01T06:22:32.010466Z',
        needs_review: true,
        unlock_date: '2016-11-01T06:22:32.010153Z',
        next_review_date: '2016-11-01T06:22:32.029204Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5412,
        vocabulary: {
          meaning: 'role',
          readings: [
            {
              character: '役割',
              kana: 'やくわり',
              level: 23,
              tags: [
                'Noun', 'Suffix',
              ],
              sentence_en: 'Duck!',
              sentence_ja: '頭を下げろ',
              jlpt: null,
              common: true,
            },
          ],
        },
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-11-01T06:22:32.083111Z',
        needs_review: true,
        unlock_date: '2016-11-01T06:22:32.082584Z',
        next_review_date: '2016-11-01T06:22:32.092060Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5413,
        vocabulary: {
          meaning: 'rules, law, order, discipline',
          readings: [
            {
              character: '規律',
              kana: 'きりつ',
              level: 23,
              tags: [
                'Noun', 'Suffix',
              ],
              sentence_en: 'Duck!',
              sentence_ja: '頭を下げろ',
              jlpt: null,
              common: true,
            },
          ],
        },
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-11-01T06:22:32.179055Z',
        needs_review: true,
        unlock_date: '2016-11-01T06:22:32.178739Z',
        next_review_date: '2016-11-01T06:22:32.199173Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5414,
        vocabulary: {
          meaning: 'power outage, cutoff of electricity, power cut',
          readings: [
            {
              character: '停電',
              kana: 'ていでん',
              level: 23,
              tags: [
                'Noun', 'Suffix',
              ],
              sentence_en: 'Duck!',
              sentence_ja: '頭を下げろ',
              jlpt: null,
              common: true,
            },
          ],
        },
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-11-01T06:22:32.256010Z',
        needs_review: true,
        unlock_date: '2016-11-01T06:22:32.255668Z',
        next_review_date: '2016-11-01T06:22:32.278914Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5416,
        vocabulary: {
          meaning: 'swamp',
          readings: [
            {
              character: '沢',
              kana: 'さわ',
              level: 23,
              tags: [
                'Noun', 'Suffix',
              ],
              sentence_en: 'Duck!',
              sentence_ja: '頭を下げろ',
              jlpt: null,
              common: true,
            },
          ],
        },
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-11-01T06:22:32.459742Z',
        needs_review: true,
        unlock_date: '2016-11-01T06:22:32.459425Z',
        next_review_date: '2016-11-01T06:22:32.485331Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5418,
        vocabulary: {
          meaning: 'to finish, to settle',
          readings: [
            {
              character: '済ます',
              kana: 'すます',
              level: 23,
              tags: [
                'Noun', 'Suffix',
              ],
              sentence_en: 'Duck!',
              sentence_ja: '頭を下げろ',
              jlpt: null,
              common: true,
            },
          ],
        },
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-11-01T06:22:32.644459Z',
        needs_review: true,
        unlock_date: '2016-11-01T06:22:32.644128Z',
        next_review_date: '2016-11-01T06:22:32.659681Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5420,
        vocabulary: {
          meaning: 'leather, hides, pelts',
          readings: [
            {
              character: '皮革',
              kana: 'ひかく',
              level: 23,
              tags: [
                'Noun', 'Suffix',
              ],
              sentence_en: 'Duck!',
              sentence_ja: '頭を下げろ',
              jlpt: null,
              common: true,
            },
          ],
        },
        correct: 1,
        incorrect: 0,
        streak: 1,
        last_studied: '2016-11-08T06:00:06.103600Z',
        needs_review: true,
        unlock_date: '2016-11-01T06:22:32.837528Z',
        next_review_date: '2016-11-08T10:15:00.114528Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5422,
        vocabulary: {
          meaning: 'ratio',
          readings: [
            {
              character: '割合',
              kana: 'わりあい',
              level: 23,
              tags: [
                'Noun', 'Suffix',
              ],
              sentence_en: 'Duck!',
              sentence_ja: '頭を下げろ',
              jlpt: null,
              common: true,
            },
          ],
        },
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-11-01T06:22:32.962052Z',
        needs_review: true,
        unlock_date: '2016-11-01T06:22:32.961743Z',
        next_review_date: '2016-11-01T06:22:32.970909Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5426,
        vocabulary: {
          meaning: 'to understand, to comprehend',
          readings: [
            {
              character: '理解する',
              kana: 'りかいする',
              level: 23,
              tags: [
                'Noun', 'Suffix',
              ],
              sentence_en: 'Duck!',
              sentence_ja: '頭を下げろ',
              jlpt: null,
              common: true,
            },
          ],
        },
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-11-01T06:22:33.290989Z',
        needs_review: true,
        unlock_date: '2016-11-01T06:22:33.290674Z',
        next_review_date: '2016-11-01T06:22:33.307366Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5427,
        vocabulary: {
          meaning: 'gentle, kind, warm hearted, nice',
          readings: [
            {
              character: '優しい',
              kana: 'やさしい',
              level: 23,
              tags: [
                'Noun', 'Suffix',
              ],
              sentence_en: 'Duck!',
              sentence_ja: '頭を下げろ',
              jlpt: null,
              common: true,
            },
          ],
        },
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-11-01T06:22:33.361456Z',
        needs_review: true,
        unlock_date: '2016-11-01T06:22:33.361140Z',
        next_review_date: '2016-11-01T06:22:33.382982Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5428,
        vocabulary: {
          meaning: 'bullet train, shinkansen',
          readings: [
            {
              character: '新幹線',
              kana: 'しんかんせん',
              level: 23,
              tags: [
                'Noun', 'Suffix',
              ],
              sentence_en: 'Duck!',
              sentence_ja: '頭を下げろ',
              jlpt: null,
              common: true,
            },
          ],
        },
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-11-01T06:22:33.444261Z',
        needs_review: true,
        unlock_date: '2016-11-01T06:22:33.443951Z',
        next_review_date: '2016-11-01T06:22:33.467429Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5431,
        vocabulary: {
          meaning: 'nurse',
          readings: [
            {
              character: '看護師',
              kana: 'かんごし',
              level: 23,
              tags: [
                'Noun', 'Suffix',
              ],
              sentence_en: 'Duck!',
              sentence_ja: '頭を下げろ',
              jlpt: null,
              common: true,
            },
          ],
        },
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-11-01T06:22:33.691593Z',
        needs_review: true,
        unlock_date: '2016-11-01T06:22:33.691277Z',
        next_review_date: '2016-11-01T06:22:33.700599Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5432,
        vocabulary: {
          meaning: 'reality',
          readings: [
            {
              character: '現実',
              kana: 'げんじつ',
              level: 23,
              tags: [
                'Noun', 'Suffix',
              ],
              sentence_en: 'Duck!',
              sentence_ja: '頭を下げろ',
              jlpt: null,
              common: true,
            },
          ],
        },
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-11-01T06:22:33.736847Z',
        needs_review: true,
        unlock_date: '2016-11-01T06:22:33.736468Z',
        next_review_date: '2016-11-01T06:22:33.748930Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5436,
        vocabulary: {
          meaning: 'ten percent',
          readings: [
            {
              character: '一割',
              kana: 'いちわり',
              level: 23,
              tags: [
                'Noun', 'Suffix',
              ],
              sentence_en: 'Duck!',
              sentence_ja: '頭を下げろ',
              jlpt: null,
              common: true,
            },
          ],
        },
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-11-01T06:22:34.104774Z',
        needs_review: true,
        unlock_date: '2016-11-01T06:22:34.104315Z',
        next_review_date: '2016-11-01T06:22:34.119444Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5438,
        vocabulary: {
          meaning: 'acting, performance',
          readings: [
            {
              character: '演技',
              kana: 'えんぎ',
              level: 23,
              tags: [
                'Noun', 'Suffix',
              ],
              sentence_en: 'Duck!',
              sentence_ja: '頭を下げろ',
              jlpt: null,
              common: true,
            },
          ],
        },
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-11-01T06:22:34.253398Z',
        needs_review: true,
        unlock_date: '2016-11-01T06:22:34.253044Z',
        next_review_date: '2016-11-01T06:22:34.262436Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5439,
        vocabulary: {
          meaning: 'castle',
          readings: [
            {
              character: '城',
              kana: 'しろ',
              level: 23,
              tags: [
                'Noun', 'Suffix',
              ],
              sentence_en: 'Duck!',
              sentence_ja: '頭を下げろ',
              jlpt: null,
              common: true,
            },
          ],
        },
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-11-01T06:22:34.324573Z',
        needs_review: true,
        unlock_date: '2016-11-01T06:22:34.324241Z',
        next_review_date: '2016-11-01T06:22:34.340431Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5440,
        vocabulary: {
          meaning: 'nipple',
          readings: [
            {
              character: '乳首',
              kana: 'ちくび',
              level: 23,
              tags: [
                'Noun', 'Suffix',
              ],
              sentence_en: 'Duck!',
              sentence_ja: '頭を下げろ',
              jlpt: null,
              common: true,
            },
          ],
        },
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-11-01T06:22:34.413397Z',
        needs_review: true,
        unlock_date: '2016-11-01T06:22:34.413048Z',
        next_review_date: '2016-11-01T06:22:34.428342Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5441,
        vocabulary: {
          meaning: 'to provide, to furnish, to equip, to prepare for',
          readings: [
            {
              character: '備える',
              kana: 'そなえる',
              level: 23,
              tags: [
                'Noun', 'Suffix',
              ],
              sentence_en: 'Duck!',
              sentence_ja: '頭を下げろ',
              jlpt: null,
              common: true,
            },
          ],
        },
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-11-01T06:22:34.508432Z',
        needs_review: true,
        unlock_date: '2016-11-01T06:22:34.508085Z',
        next_review_date: '2016-11-01T06:22:34.529582Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5442,
        vocabulary: {
          meaning: 'preparations',
          readings: [
            {
              character: '準備',
              kana: 'じゅんび',
              level: 23,
              tags: [
                'Noun', 'Suffix',
              ],
              sentence_en: 'Duck!',
              sentence_ja: '頭を下げろ',
              jlpt: null,
              common: true,
            },
          ],
        },
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-11-01T06:22:34.583495Z',
        needs_review: true,
        unlock_date: '2016-11-01T06:22:34.582822Z',
        next_review_date: '2016-11-01T06:22:34.592528Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5444,
        vocabulary: {
          meaning: 'physical law, law',
          readings: [
            {
              character: '法則',
              kana: 'ほうそく',
              level: 23,
              tags: [
                'Noun', 'Suffix',
              ],
              sentence_en: 'Duck!',
              sentence_ja: '頭を下げろ',
              jlpt: null,
              common: true,
            },
          ],
        },
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-11-01T06:22:34.762127Z',
        needs_review: true,
        unlock_date: '2016-11-01T06:22:34.761812Z',
        next_review_date: '2016-11-01T06:22:34.781117Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5445,
        vocabulary: {
          meaning: 'to divide',
          readings: [
            {
              character: '割る',
              kana: 'わる',
              level: 23,
              tags: [
                'Noun', 'Suffix',
              ],
              sentence_en: 'Duck!',
              sentence_ja: '頭を下げろ',
              jlpt: null,
              common: true,
            },
          ],
        },
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-11-01T06:22:34.861161Z',
        needs_review: true,
        unlock_date: '2016-11-01T06:22:34.860852Z',
        next_review_date: '2016-11-01T06:22:34.875958Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5446,
        vocabulary: {
          meaning: 'to increase something, to increase',
          readings: [
            {
              character: '増やす',
              kana: 'ふやす',
              level: 23,
              tags: [
                'Noun', 'Suffix',
              ],
              sentence_en: 'Duck!',
              sentence_ja: '頭を下げろ',
              jlpt: null,
              common: true,
            },
          ],
        },
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-11-01T06:22:34.951980Z',
        needs_review: true,
        unlock_date: '2016-11-01T06:22:34.951627Z',
        next_review_date: '2016-11-01T06:22:34.961590Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5447,
        vocabulary: {
          meaning: 'dwelling, residence',
          readings: [
            {
              character: '住宅',
              kana: 'じゅうたく',
              level: 23,
              tags: [
                'Noun', 'Suffix',
              ],
              sentence_en: 'Duck!',
              sentence_ja: '頭を下げろ',
              jlpt: null,
              common: true,
            },
          ],
        },
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-11-01T06:22:35.027403Z',
        needs_review: true,
        unlock_date: '2016-11-01T06:22:35.027078Z',
        next_review_date: '2016-11-01T06:22:35.036734Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5453,
        vocabulary: {
          meaning: 'to elect',
          readings: [
            {
              character: '選挙する',
              kana: 'せんきょする',
              level: 23,
              tags: [
                'Noun', 'Suffix',
              ],
              sentence_en: 'Duck!',
              sentence_ja: '頭を下げろ',
              jlpt: null,
              common: true,
            },
          ],
        },
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-11-01T06:22:35.503063Z',
        needs_review: true,
        unlock_date: '2016-11-01T06:22:35.502668Z',
        next_review_date: '2016-11-01T06:22:35.512621Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5454,
        vocabulary: {
          meaning: 'to cut off',
          readings: [
            {
              character: '断つ',
              kana: 'たつ',
              level: 23,
              tags: [
                'Noun', 'Suffix',
              ],
              sentence_en: 'Duck!',
              sentence_ja: '頭を下げろ',
              jlpt: null,
              common: true,
            },
          ],
        },
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-11-01T06:22:35.553795Z',
        needs_review: true,
        unlock_date: '2016-11-01T06:22:35.553467Z',
        next_review_date: '2016-11-01T06:22:35.565934Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5455,
        vocabulary: {
          meaning: 'economic, financial, economical',
          readings: [
            {
              character: '経済的',
              kana: 'けいざいてき',
              level: 23,
              tags: [
                'Noun', 'Suffix',
              ],
              sentence_en: 'Duck!',
              sentence_ja: '頭を下げろ',
              jlpt: null,
              common: true,
            },
          ],
        },
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-11-01T06:22:35.632481Z',
        needs_review: true,
        unlock_date: '2016-11-01T06:22:35.631890Z',
        next_review_date: '2016-11-01T06:22:35.647388Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5456,
        vocabulary: {
          meaning: 'current location, current place, actual spot, present location',
          readings: [
            {
              character: '現場',
              kana: 'げんば',
              level: 23,
              tags: [
                'Noun', 'Suffix',
              ],
              sentence_en: 'Duck!',
              sentence_ja: '頭を下げろ',
              jlpt: null,
              common: true,
            },
          ],
        },
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-11-01T06:22:35.692788Z',
        needs_review: true,
        unlock_date: '2016-11-01T06:22:35.692475Z',
        next_review_date: '2016-11-01T06:22:35.702013Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5458,
        vocabulary: {
          meaning: 'personnel, staff, employee',
          readings: [
            {
              character: '職員',
              kana: 'しょくいん',
              level: 23,
              tags: [
                'Noun', 'Suffix',
              ],
              sentence_en: 'Duck!',
              sentence_ja: '頭を下げろ',
              jlpt: null,
              common: true,
            },
          ],
        },
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-11-01T06:22:35.852730Z',
        needs_review: true,
        unlock_date: '2016-11-01T06:22:35.852345Z',
        next_review_date: '2016-11-01T06:22:35.871648Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5459,
        vocabulary: {
          meaning: 'employed',
          readings: [
            {
              character: '有職',
              kana: 'ゆうしょく',
              level: 23,
              tags: [
                'Noun', 'Suffix',
              ],
              sentence_en: 'Duck!',
              sentence_ja: '頭を下げろ',
              jlpt: null,
              common: true,
            },
          ],
        },
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-11-01T06:22:35.946343Z',
        needs_review: true,
        unlock_date: '2016-11-01T06:22:35.946032Z',
        next_review_date: '2016-11-01T06:22:35.964023Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5460,
        vocabulary: {
          meaning: 'resignation, quitting',
          readings: [
            {
              character: '辞職',
              kana: 'じしょく',
              level: 23,
              tags: [
                'Noun', 'Suffix',
              ],
              sentence_en: 'Duck!',
              sentence_ja: '頭を下げろ',
              jlpt: null,
              common: true,
            },
          ],
        },
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-11-01T06:22:36.021663Z',
        needs_review: true,
        unlock_date: '2016-11-01T06:22:36.021338Z',
        next_review_date: '2016-11-01T06:22:36.035542Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5462,
        vocabulary: {
          meaning: 'to conserve, to protect',
          readings: [
            {
              character: '保護する',
              kana: 'ほごする',
              level: 23,
              tags: [
                'Noun', 'Suffix',
              ],
              sentence_en: 'Duck!',
              sentence_ja: '頭を下げろ',
              jlpt: null,
              common: true,
            },
          ],
        },
        correct: 0,
        incorrect: 0,
        streak: 0,
        last_studied: '2016-11-01T06:22:36.289871Z',
        needs_review: true,
        unlock_date: '2016-11-01T06:22:36.289559Z',
        next_review_date: '2016-11-01T06:22:36.305271Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      }, {
        id: 5463,
        vocabulary: {
          meaning: 'leather',
          readings: [
            {
              character: '革',
              kana: 'かわ',
              level: 23,
              tags: [
                'Noun', 'Suffix',
              ],
              sentence_en: 'Duck!',
              sentence_ja: '頭を下げろ',
              jlpt: null,
              common: true,
            },
          ],
        },
        correct: 1,
        incorrect: 0,
        streak: 1,
        last_studied: '2016-11-08T05:52:20.045546Z',
        needs_review: true,
        unlock_date: '2016-11-01T06:22:36.376681Z',
        next_review_date: '2016-11-08T10:00:00.057828Z',
        burned: false,
        hidden: false,
        wanikani_srs: 'burned',
        wanikani_srs_numeric: 9,
        wanikani_burned: true,
      },
    ],
  },
};
